blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/HMB-research/x-ray-crawler/discussions
    about: Ask questions or discuss ideas
  - name: Security Vulnerability
    url: https://github.com/HMB-research/x-ray-crawler/security/advisories/new
    about: Report a security vulnerability (private disclosure)
  - name: Documentation
    url: https://github.com/HMB-research/x-ray-crawler#readme
    about: Read the documentation
