name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'NPM dist-tag (latest, beta, alpha, next)'
        required: false
        default: 'latest'
        type: choice
        options:
          - latest
          - beta
          - alpha
          - next

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Build package
        run: |
          if grep -q '"build"' package.json; then
            npm run build
          else
            echo "No build script found, skipping..."
          fi
        continue-on-error: true

      - name: Publish to NPM (latest)
        if: github.event_name == 'release' || github.event.inputs.npm_tag == 'latest'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM (tagged)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.npm_tag != 'latest'
        run: npm publish --provenance --access public --tag ${{ github.event.inputs.npm_tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify on success
        if: success()
        run: |
          echo "✅ Package published successfully!"
          echo "Version: $(node -p "require('./package.json').version")"
          echo "Tag: ${{ github.event.inputs.npm_tag || 'latest' }}"
